create table Person(
    id int primary key generated by default as identity,
    username varchar not null,
    year_of_birth integer not null,
    password varchar not null,
    role varchar not null,
    registration_date timestamp not null,
    name varchar not null,
    email varchar not null
);

insert into Person (username, year_of_birth, password, role, registration_date, name, email)
values ('admin', 2002, 'admin', 'ROLE_ADMIN', current_timestamp, 'admin', 'admin@gmail.com');

create table Plane(
    id int primary key generated by default as identity,
    model varchar not null,
    capacity integer not null,
    production_year integer not null
);

create table Ticket(
    id int primary key generated by default as identity,
    person_id integer references Person(id) on delete set null,
    plane_id integer references Ticket(id) on delete set null,
    departure varchar not null,
    arrival varchar not null
)